<?php

namespace CRUD\InventoryBundle\Repository;

/**
 * TrimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrimRepository extends \Doctrine\ORM\EntityRepository
{
}
